[build]
  environment = { NODE_VERSION = "20", RUBY_VERSION = "3.0.0" }
  publish = "docs/_site/"
  command = "./scripts/build-netlify-pr-preview.sh"

[[redirects]]
  from = "/"
  to = "/design-system"
  status = 302
