backend:
  name: github
  repo: test-things/design-system
  branch: master
  site_domain: localhost:4000
  base_url: https://netlifycms-auth.glitch.me

publish_mode: editorial_workflow
media_folder: images/uploads

collections:
  - name: 'page-component'
    label: 'Page components'
    label_singular: 'Page component'
    folder: 'components/'
    create: true
    slug: '{{slug}}'
    fields:
      - {name: 'title', label: 'Title', widget: 'string'}
      - {name: 'slug', label: 'Slug', widget: 'slugWidget'}
      - {name: 'layout', value: 'page', widget: 'hidden'}
      - {name: 'category', value: 'Page components', widget: 'hidden'}
      - name: 'status'
        label: 'Implementation status'
        widget: 'statusWidget'
        options:
          - label: 'Proposed'
            value: 'proposed'
          - label: 'In progress'
            value: 'in-progress'
          - label: 'Beta'
            value: 'beta'
          - label: 'Released'
            value: 'released'
      - {name: 'intro', label: 'Intro text', widget: 'introWidget'}
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation'
            label: 'Variation'
            widget: 'variationWidget'
      - {name: 'usage', label: 'Usage', widget: 'usageWidget'}
      - {name: 'accessibility', label: 'Accessibility', widget: 'accessibilityWidget'}
      - {name: 'research', label: 'Research', widget: 'researchWidget'}
