backend:
  name: github
  repo: test-things/design-system
  branch: master
  squash_merges: true
  base_url: https://netlifycms-auth.glitch.me

logo_url: https://cfpb.github.io/design-manual/static/img/logo/Logo0_@2.png
publish_mode: editorial_workflow
media_folder: docs/images/uploads

collections:
  - name: 'components'
    label: 'Components'
    label_singular: 'Component'
    folder: 'docs/components/'
    create: true
    delete: false
    slug: '{{slug}}'
    filter: {field: 'layout', value: 'component'}
    fields:
      - {name: 'title', label: 'Title', widget: 'string'}
      - {name: 'layout', value: 'component', widget: 'hidden'}
      - {name: 'section', value: 'components', widget: 'hidden'}
      - name: 'category'
        label: 'Component category'
        widget: 'select'
        options:
          - label: 'Alerts'
            value: 'alerts'
          - label: 'Data visualization'
            value: 'data-visualization'
          - label: 'Forms'
            value: 'forms'
          - label: 'Layout'
            value: 'layout'
          - label: 'Tables'
            value: 'tables'
          - label: 'Text'
            value: 'text'
          - label: 'Widgets'
            value: 'widgets'
      - name: 'status'
        label: 'Implementation status'
        widget: 'statusWidget'
        options:
          - label: 'Proposed'
            value: 'Proposed'
          - label: 'In progress'
            value: 'In progress'
          - label: 'Beta'
            value: 'Beta'
          - label: 'Released'
            value: 'Released'
      - {name: 'intro', label: 'Intro text', widget: 'introWidget'}
      - name: 'variations'
        label: 'Variations'
        widget: 'list'
        fields:
          - name: 'variation_name'
            label: 'Variation name'
            widget: 'variationNameWidget'
          - name: 'variation_description'
            label: 'Variation description'
            widget: 'variationDescriptionWidget'
          - name: 'variation_code_snippet'
            label: 'Variation code snippet'
            widget: 'variationCodeSnippetWidget'
      - {name: 'usage', label: 'Usage', widget: 'usageWidget'}
      - {name: 'accessibility', label: 'Accessibility', widget: 'accessibilityWidget'}
      - {name: 'research', label: 'Research', widget: 'researchWidget'}
