name: GitHub Pages

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - uses: ruby/setup-ruby@v1.81.0
          with:
            ruby-version: '2.7.1'
        - uses: actions/checkout@v3
        - run: ./scripts/update-gh-pages.sh
          env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
