name: GitHub Pages

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - uses: actions/setup-ruby@v2
          with:
            ruby-version: '2.6'
        - uses: actions/checkout@v2
        - run: ./scripts/update-gh-pages.sh
          env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
