name: Publish to Github Package Registry

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Config Git
        run: |
          git config --global user.name "CFPBot"
          git config --global user.email "CFPBot@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install

      - name: Build assets
        run: yarn build-packages

      - name: Publish
        run: |
          yarn lerna publish patch --yes --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
