name: Publish to Github Package Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Config Git
        run: |
          git config --global user.name "CFPBot"
          git config --global user.email "CFPBot@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build styles
        run: yarn run gulp styles

      - name: Publish
        run: |
          yarn run lerna publish patch --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
