name: Publish to Github Package Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build
        run: yarn run gulp styles

      - name: Add auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${TOKEN}" > .npmrc
          echo '@cfpb:registry=https://npm.pkg.github.com' >> .npmrc
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Publish
        run: |
          git config --global user.name "CFPBot"
          git config --global user.email "CFPBot@users.noreply.github.com"
          yarn run lerna publish patch --yes
