name: Sauce CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  browser-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Bundler
        run: gem install bundler

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Start local Design System website server
        run: |
          yarn start &
          sleep 5

      - name: Run browser tests
        # Don't run these tests on forks. It would be nice to instead check
        # to see if the Sauce Labs environment variables are defined, but that
        # doesn't seem currently possible:
        # https://github.com/actions/runner/issues/520
        if: ${{ github.repository_owner == 'cfpb' }}
        run: yarn test:browser:cloud
