apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
npm:
  registries:
    - url: https://registry.npmjs.org
  packages:
    '@cfpb/browserslist-config': '0.0.2'
sauce:
  region: us-west-1
  concurrency: 15
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.js
  version: 13.7.3
  record: false
  key: ''
  reporters: []
suites:
  - name: cypress - Windows 10 - chrome
    browser: 'chrome'
    browserVersion: 'latest'
    platformName: 'Windows 10'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      # Increase the VM's resolution for Decap CMS tests that require a wider viewport.
      screenResolution: '1920x1200'
  - name: cypress - Windows 11 - edge
    browser: 'microsoftedge'
    browserVersion: '119'
    platformName: 'Windows 11'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      screenResolution: '1920x1200'
      exclude:
        # Decap CMS is only tested with Chrome
        - 'test/cypress/e2e/docs/decap-cms.cy.js'
  - name: cypress - Windows 10 - firefox
    browser: 'firefox'
    browserVersion: '123'
    platformName: 'Windows 10'
    config:
      testingType: e2e
      specPattern:
        - 'test/cypress/e2e/**/*.cy.js'
      screenResolution: '1920x1200'
      exclude:
        # Decap CMS is only tested with Chrome
        - 'test/cypress/e2e/docs/decap-cms.cy.js'
rootDir: .
